image: cprov/stoq:candidate

services:
    - postgres:9.5

variables:
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # Fetch utils/ submodule
  GIT_SUBMODULE_STRATEGY: recursive
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  STOQLIB_TEST_HOSTNAME: "postgres"
  STOQLIB_TEST_DBNAME: "test"
  STOQLIB_TEST_USERNAME: "test"
  STOQLIB_TEST_PASSWORD: ""
  # Setuptools 50 broke the tests. This is a quick workaround. See more at
  # https://stackoverflow.com/questions/63663362/django-python3-on-install-i-get-parent-module-setuptools-not-loaded
  SETUPTOOLS_USE_DISTUTILS: stdlib


stages:
  - test
  - build

before_script:
  - python3 -V
  - export LC_ALL=pt_BR.UTF-8
  # Some tests assume the timezone is America/Sao_Paulo. This can go away if we remove the old nfe plugin
  - ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
  - dpkg-reconfigure --frontend noninteractive tzdata
  # Install testing requirements
  - easy_install3 pip
  - pip3 install -Ur requirements-test.txt
  - pip3 install -U setuptools pip wheel
  # Install tools to create debian packages
  - apt update
  - apt --yes install build-essential devscripts debhelper python3-all libcairo2-dev libgirepository1.0-dev
  - python3 setup.py develop
  - pip3 freeze

test:
  stage: test
  script:
    - xvfb-run make coverage

build_dist:
  stage: build
  script:
    # Install bdist requirements with pip.
    - pip3 install -U kiwi-gtk wheel setuptools
    - python3 setup.py bdist_wheel

  artifacts:
    paths:
      - dist

generate_deb:
  stage: build
  script:
    - rm -rf dist
    - make deb

  artifacts:
    paths:
      - dist/*.deb
  only:
    - master

manual_generate_deb:
  stage: build
  script:
    - rm -rf dist
    - make deb

  artifacts:
    paths:
      - dist/*.deb
  when: manual
