from kiwi.ui.test.player import Player

player = Player(['bin/stoq', 'warehouse'])
app = player.get_app()

player.wait_for_window("WarehouseApp")
app.WarehouseApp.search_button.clicked()
app.WarehouseApp.products.select_paths([(0,)])
app.WarehouseApp.products.select_paths([])
app.WarehouseApp.products.select_paths([(0,)])
app.WarehouseApp.filter_combo.select_item_by_label("Mad dog")
app.WarehouseApp.products.select_paths([])
app.WarehouseApp.products.select_paths([(0,)])
app.WarehouseApp.filter_combo.select_item_by_label("The dude")
app.WarehouseApp.products.select_paths([])
app.WarehouseApp.products.select_paths([(0,)])
app.WarehouseApp.filter_combo.select_item_by_label("Mickey Mouse")
app.WarehouseApp.products.select_paths([])
app.WarehouseApp.products.select_paths([(0,)])
app.WarehouseApp.filter_combo.select_item_by_label("John Wayne")
app.WarehouseApp.products.select_paths([])
app.WarehouseApp.products.select_paths([(0,)])
app.WarehouseApp.filter_combo.select_item_by_label("CURRENT_BRANCH")
app.WarehouseApp.retention_button.clicked()
app.WarehouseApp.history_button.clicked()
app.WarehouseApp.SearchMenu.activate()
app.WarehouseApp.transfer_action.activate()
app.WarehouseApp.SalesMenu.activate()
app.WarehouseApp.SearchMenu.activate()
app.WarehouseApp.users_menu.activate()
app.WarehouseApp.ClearCookie.activate()
app.WarehouseApp.users_menu.activate()
app.WarehouseApp.StoreCookie.activate()
app.WarehouseApp.SalesMenu.activate()
app.WarehouseApp.SearchMenu.activate()
app.WarehouseApp.users_menu.activate()
app.WarehouseApp.SalesMenu.activate()
app.WarehouseApp.Quit.activate()
player.finish()
