from kiwi.ui.test.player import Player

player = Player(['bin/stoq', 'pos'])
app = player.get_app()

player.wait_for_window("POSApp")
app.POSApp.new_order_button.clicked()

player.wait_for_window("NewOrderEditor")
app.NewOrderEditor.anonymous_check.clicked()
app.NewOrderEditor.client_check.clicked()
app.NewOrderEditor.client.set_text("a")
app.NewOrderEditor.client.set_text("")
app.NewOrderEditor.client.set_text("John Wayne")
app.NewOrderEditor.ok_button.clicked()
player.delete_window("NewOrderEditor")

app.POSApp.product.set_text("a")
app.POSApp.product.set_text("")
app.POSApp.product.set_text("K15 Keyboard AXDR")
app.POSApp.product.activate()
app.POSApp.quantity.set_text("")
app.POSApp.quantity.set_text("2.00")
app.POSApp.quantity.set_text("")
app.POSApp.quantity.set_text("3.00")
app.POSApp.quantity.activate()
app.POSApp.sellables.select_paths(['0'])
app.POSApp.quantity.set_text("")
app.POSApp.quantity.set_text("1.00")
app.POSApp.product.set_text("")
app.POSApp.product.set_text("")
app.POSApp.product.set_text("a")
app.POSApp.product.set_text("")
app.POSApp.product.set_text("M73 Optical Mouse 45FG")
app.POSApp.product.activate()
app.POSApp.quantity.set_text("")
app.POSApp.quantity.set_text("2.00")
app.POSApp.quantity.activate()
app.POSApp.sellables.select_paths(['1'])
app.POSApp.quantity.set_text("")
app.POSApp.quantity.set_text("1.00")
app.POSApp.product.set_text("")
app.POSApp.product.set_text("")
app.POSApp.delivery_button.clicked()

player.wait_for_window("DeliveryEditor")
app.DeliveryEditor.price.set_text("")
app.DeliveryEditor.price.set_text("1")
app.DeliveryEditor.price.set_text("10")
app.DeliveryEditor.klist.select_paths([(0,)])
app.DeliveryEditor.klist.select_paths([(0,)])
app.DeliveryEditor.klist.double_click(0)

player.wait_for_window("SellableItemEditor")
app.SellableItemEditor.quantity.set_text("")
app.SellableItemEditor.quantity.set_text("2.00")
app.SellableItemEditor.quantity.set_text("")
app.SellableItemEditor.quantity.set_text("1.00")
app.SellableItemEditor.ok_button.clicked()
app.DeliveryEditor.klist.select_paths([])
app.DeliveryEditor.klist.select_paths([(0,)])
player.delete_window("SellableItemEditor")

app.DeliveryEditor.klist.select_paths([(1,)])
app.DeliveryEditor.delete_button.clicked()

player.wait_for_window("ConfirmDialog")
app.ConfirmDialog.ok_button.clicked()
app.DeliveryEditor.klist.select_paths([])
player.delete_window("ConfirmDialog")

app.DeliveryEditor.ok_button.clicked()
app.POSApp.sellables.select_paths(['2'])
player.delete_window("DeliveryEditor")

app.POSApp.delivery_button.clicked()

player.wait_for_window("DeliveryEditor")
app.DeliveryEditor.klist.select_paths([(0,)])
app.DeliveryEditor.klist.select_paths([(0,)])
app.DeliveryEditor.klist.select_paths([(0,)])
app.DeliveryEditor.klist.double_click(0)

player.wait_for_window("SellableItemEditor")
app.SellableItemEditor.quantity.set_text("")
app.SellableItemEditor.quantity.set_text("1.00")
app.SellableItemEditor.ok_button.clicked()
app.DeliveryEditor.klist.select_paths([])
app.DeliveryEditor.klist.select_paths([(0,)])
player.delete_window("SellableItemEditor")

app.DeliveryEditor.klist.select_paths([(1,)])
app.DeliveryEditor.klist.select_paths([(1,)])
app.DeliveryEditor.klist.double_click(1)

player.wait_for_window("SellableItemEditor")
app.SellableItemEditor.quantity.set_text("")
app.SellableItemEditor.quantity.set_text("1.00")
app.SellableItemEditor.ok_button.clicked()
app.DeliveryEditor.klist.select_paths([])
app.DeliveryEditor.klist.select_paths([(1,)])
player.delete_window("SellableItemEditor")

app.DeliveryEditor.ok_button.clicked()
app.POSApp.sellables.select_paths(['3'])
player.delete_window("DeliveryEditor")

app.POSApp.delivery_button.clicked()

player.wait_for_window("DeliveryEditor")
app.DeliveryEditor.klist.select_paths([(0,)])
app.DeliveryEditor.ok_button.clicked()
app.POSApp.sellables.select_paths(['4'])
player.delete_window("DeliveryEditor")

app.POSApp.sellables.select_paths(['3'])
app.POSApp.remove_item_button.clicked()
app.POSApp.sellables.select_paths([])
app.POSApp.sellables.select_paths(['0'])
app.POSApp.delivery_button.clicked()

player.wait_for_window("DeliveryEditor")
app.DeliveryEditor.klist.select_paths([(1,)])
app.DeliveryEditor.ok_button.clicked()
app.POSApp.sellables.select_paths(['4'])
player.delete_window("DeliveryEditor")

app.POSApp.sellables.select_paths(['2'])
app.POSApp.remove_item_button.clicked()
app.POSApp.sellables.select_paths([])
app.POSApp.sellables.select_paths(['0'])
app.POSApp.sellables.select_paths(['2'])
app.POSApp.remove_item_button.clicked()
app.POSApp.sellables.select_paths([])
app.POSApp.sellables.select_paths(['0'])
app.POSApp.sellables.select_paths(['2'])
app.POSApp.remove_item_button.clicked()
app.POSApp.sellables.select_paths([])
app.POSApp.sellables.select_paths(['0'])
app.POSApp.delivery_button.clicked()

player.wait_for_window("DeliveryEditor")
app.DeliveryEditor.price.set_text("")
app.DeliveryEditor.price.set_text("1")
app.DeliveryEditor.price.set_text("10")
app.DeliveryEditor.price.activate()
app.DeliveryEditor.klist.select_paths([(1,)])
app.DeliveryEditor.ok_button.clicked()
app.POSApp.sellables.select_paths(['2'])
player.delete_window("DeliveryEditor")

app.POSApp.SalesMenu.activate()
app.POSApp.Quit.activate()
player.finish()
