#!/usr/bin/env python2

import sys
from xml.etree import ElementTree

filename = None
line_no = 0

modified_files = {}
for line in sys.stdin.readlines():
    if line.startswith('--- '):
        continue
    if line.startswith('+++ '):
        continue

    if line.startswith('diff --git '):
        filename = line.split()[2]
    elif line.startswith('@@') and line.count('@@') == 2:
        line_no = int(line.split()[2].split(',')[0][1:])
    elif line[0] in '+- ':
        if line.startswith('+'):
            modified_files.setdefault(filename, []).append((line_no, line[1:-1]))
        if not line.startswith('-'):
            line_no += 1

coverage_files = {}
tree = ElementTree.parse(sys.argv[1])
for node in tree.findall('.//class'):
    filename = node.attrib['filename']
    coverage = dict([(int(line.attrib['number']), line.attrib['hits'] == '1')
                     for line in node.findall('.//lines/line')])
    coverage_files[filename] = coverage

untested = []

for filename, lines in modified_files.items():
    if '/test/' in filename:
        continue
    coverage = coverage_files.get(filename)
    if coverage is None:
        continue
    for line, data in lines:
        covered = coverage.get(line, True)
        if covered is False:
            untested.append((filename, line, data))

for filename, line, data in sorted(untested):
    print('%s:%s:%s' % (filename, line, data))
print('-' * 80)
print(len(untested), 'untested lines')
